image: docker:latest

services:
  - docker:dind

include:
  template: SAST.gitlab-ci.yml

before_script:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

build:
  script:
    - docker build -t felipegreggio/imc-app:latest .
    - docker push felipegreggio/imc-app:latest
