stages:
  - build
  - test
  - deploy

# Include templates
include:
  - template: SAST.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

# Custom build job
build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t felipegreggio/imc-app:latest .
    - docker push felipegreggio/imc-app:latest

# DAST job
dast_job:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker run -d -p 8080:80 felipegreggio/imc-app:latest
    - sleep 10  
  variables:
    DAST_WEBSITE: "http://localhost:8080/index.html"

# Override the stage for the dast job from the DAST.gitlab-ci.yml template
dast:
  stage: test


alert:
  stage: Deploy
  after_script:
    - chmod +x telegram.sh
    - ./telegram_notification.sh
  script:
    - echo "send message to telegram!"
