stages:
  - build
  - test

# Custom build job
build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t felipegreggio/imc-app:latest .
    - docker push felipegreggio/imc-app:latest

# SAST job
include:
  template: SAST.gitlab-ci.yml
